name: Build and Push Docker Images

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./backend
          tags: erasme/itineraires-multicriteres-backend:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }} , erasme/itineraires-multicriteres-backend:${{ github.sha }}

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./frontend/
          tags: erasme/itineraires-multicriteres-frontend:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }} , erasme/itineraires-multicriteres-frontend:${{ github.sha }}

  redeploy-back:
      name: Redeploy back Workload
      runs-on: ubuntu-latest
      needs: push_to_registry
      steps:
        - name: Make API Request
          uses: fjogeleit/http-request-action@master
          with:
            url: ${{ secrets.RANCHER_BASE_URL }}/v3/project/c-m-ls255pvz:p-8wdk6/workloads/deployment:itineraire-multicriteres:back?action=redeploy
            method: 'POST'
            bearerToken: ${{ secrets.RANCHER_TOKEN }}
            data: '{"scale": 2}'
  redeploy-front:
    name: Redeploy front Workload
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Make API Request
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.RANCHER_BASE_URL }}/v3/project/c-m-ls255pvz:p-8wdk6/workloads/deployment:itineraire-multicriteres:front?action=redeploy
          method: 'POST'
          bearerToken: ${{ secrets.RANCHER_TOKEN }}
          data: '{"scale": 2}'