name: Build and Push Docker Images

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  backend:
  runs-on: ubuntu-latest
  steps:
    -
    name: Checkout
    uses: actions/checkout@v2
    -
    name: Set up QEMU
    uses: docker/setup-qemu-action@v3
    -
    name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3
    -
    name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
    name: Build and push
    uses: docker/build-push-action@v5
    with:
      push: true
      context: ./backend
      # based on branch push tag latest for main and dev for dev
      tags: erasme/itineraires-multicriteres-backend:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }} , erasme/itineraires-multicriteres-backend:${{ github.sha }}
frontend:
  runs-on: ubuntu-latest
  steps:
    -
    name: Checkout
    uses: actions/checkout@v2
    -
    name: Set up QEMU
    uses: docker/setup-qemu-action@v3
    -
    name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3
    -
    name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
    name: Build and push
    uses: docker/build-push-action@v5
    with:
      push: true
      context: ./frontend
      # based on branch push tag latest for main and dev for dev
      tags: erasme/itineraires-multicriteres-frontend:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }} , erasme/itineraires-multicriteres-frontend:${{ github.sha }}
